CREATE TABLE "TB_MEMBER" (
 MEMBER_NO NUMBER PRIMARY KEY,
 MEMBER_ID VARCHAR2(20) UNIQUE,
 MEMBER_PW VARCHAR2(20) NOT NULL,
 MEMBER_NAME VARCHAR2(30) NOT NULL,
 MEMBER_SSN CHAR(14) NOT NULL, 
 ENROLL_DATE DATE DEFAULT SYSDATE,
);


COMMENT ON COLUMN TB_MEMBER.MEMBER_NO     IS '사용자 번호';
COMMENT ON COLUMN TB_MEMBER.MEMBER_ID     IS '사용자 아이디';
COMMENT ON COLUMN TB_MEMBER.MEMBER_PW     IS '사용자 비밀번호';
COMMENT ON COLUMN TB_MEMBER.MEMBER_NAME   IS '사용자 이름';
COMMENT ON COLUMN TB_MEMBER.MEMBER_SSN IS '사용자 주민등록번호';
COMMENT ON COLUMN TB_MEMBER.ENROLL_DATE IS '사용자 가입일';
COMMENT ON COLUMN TB_MEMBER.TODO_NO IS '사용자 전용 TODO 번호';


CREATE TABLE "TB_TODO" (
 TODO_TITLE VARCHAR2(20) NOT NULL,
 TODO_DO NVARCHAR2(2000) NOT NULL,
 TODO_YN VARCHAR2(30) NOT NULL,
 TODO_DATE DATE DEFAULT SYSDATE
 MEMBER_NO NUMBER
);


COMMENT ON COLUMN TB_TODO.TODO_NO     IS 'TODO 번호';
COMMENT ON COLUMN TB_TODO.TODO_TITLE     IS 'TODO 제목';
COMMENT ON COLUMN TB_TODO.TODO_DO     IS 'TODO 할일';
COMMENT ON COLUMN TB_TODO.TODO_YN   IS 'TODO 완료여부';
COMMENT ON COLUMN TB_TODO.TODO_DATE IS 'TODO 작성일';

-- TB_MEMBER와 TB_TODO에 들어갈 TODO_NO에 삽입될 시퀀스 생성
CREATE SEQUENCE SEQ_TODO_NO NOCACHE;
SELECT * FROM TB_MEMBER;
SELECT * FROM TB_TODO;
--; 샘플 데이터 INSERT
INSERT INTO TB_MEMBER 
VALUES(SEQ_TODO_NO.NEXTVAL, 'user01', 'pass01', '유저일', '960205-1196612', DEFAULT);

DELETE TB_MEMBER WHERE MEMBER_NO = 1;
ROLLBACK;
ALTER TABLE TB_TODO MODIFY TODO_YN DEFAULT 'N';